user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"